Catkin-ProjectName: object_recognition_core
Version: 0.3.1
Description: Object_recognition_core contains tools to launch several recognition pipelines, train objects, store models ...
Author: Ethan Rublee <erublee@willowgarage.com>, Vincent Rabaud <vrabaud@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://ecto.willowgarage.com/recognition

Depends: actionlib, boost, catkin, curl, ecto, ecto_ros, ecto_image_pipeline, object_recognition_msgs, pcl

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
